/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class AuthenticationButttons extends javax.swing.JPanel {
    
    public JPanel jframe1;

    /**
     * Creates new form AuthenticationButttons
     */
    public AuthenticationButttons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gotoSignin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gotoSignin.setBackground(new java.awt.Color(0, 0, 0));
        gotoSignin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        gotoSignin.setForeground(new java.awt.Color(255, 245, 220));
        gotoSignin.setText("Sign In");
        gotoSignin.setBorder(null);
        gotoSignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoSigninMouseClicked(evt);
            }
        });
        gotoSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoSigninActionPerformed(evt);
            }
        });
        jPanel1.add(gotoSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gotoSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoSigninActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gotoSigninActionPerformed

    private void gotoSigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoSigninMouseClicked
       // Instantiate the Login JPanel
   Login loginPanel = new Login();
    
    // Get the parent container of AuthenticationButtons
    Container parentContainer = getParent();
    
    // Remove AuthenticationButtons from its parent container
    parentContainer.remove(this);
    
    // Add the Login panel to the parent container in place of AuthenticationButtons
    parentContainer.add(loginPanel);
    
    // Repaint the parent container to reflect the changes
    parentContainer.revalidate();
    parentContainer.repaint();
    }//GEN-LAST:event_gotoSigninMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gotoSignin;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
